version: '3'

services:
  # Frontend service
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: always
    networks:
      - studify-network

  # Backend service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/studify
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=90d
      - CORS_ORIGIN=http://frontend:3000
    depends_on:
      - mongo
    restart: always
    networks:
      - studify-network

  # MongoDB service
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - studify-network

networks:
  studify-network:
    driver: bridge

volumes:
  mongo-data:
