version: '3'

services:
  # Frontend service
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: always
    networks:
      - studyify-network

  # Backend service
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/studyify
      - JWT_SECRET=studyify_jwt_secret_key_2025
      - JWT_EXPIRES_IN=90d
      - CORS_ORIGIN=http://frontend:3000
    depends_on:
      - mongo
    restart: always
    networks:
      - studyify-network

  # MongoDB service
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - studyify-network

  # Nginx service for SSL termination and routing
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.studyify.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/letsencrypt
      - ./logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - studyify-network

networks:
  studyify-network:
    driver: bridge

volumes:
  mongo-data:
