name: studyify.in CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test
        
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm ci
        
    - name: Run Backend Tests
      run: |
        cd backend
        npm test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build
        
    - name: Build Backend
      run: |
        cd backend
        npm ci
        
    - name: Upload Frontend Build
      uses: actions/upload-artifact@v2
      with:
        name: frontend-build
        path: frontend/.next
        
    - name: Upload Backend Build
      uses: actions/upload-artifact@v2
      with:
        name: backend-build
        path: backend/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Download Frontend Build
      uses: actions/download-artifact@v2
      with:
        name: frontend-build
        path: frontend/.next
        
    - name: Download Backend Build
      uses: actions/download-artifact@v2
      with:
        name: backend-build
        path: backend/
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: studyify/frontend:latest
        
    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: studyify/backend:latest
        
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/studyify
          docker-compose pull
          docker-compose up -d
